name: cellar
description: Project Cellar

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_image_picker: ^4.6.7
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  intl: ^0.16.1
  carousel_slider: ^2.2.1
  cached_network_image: ^2.2.0+1
  permission_handler: 5.0.1+1

  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  rename: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: "assets/images/splash.png"
  color: "607D8B"
  android: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
