name: cellar
description: Project Cellar

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  multi_image_picker: ^4.7.14
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1
  firebase_crashlytics: ^0.2.1+1
  cloud_firestore: ^0.14.0+2
  google_sign_in: ^4.5.4
  apple_sign_in: ^0.1.0
  shared_preferences: ^0.5.12
  intl: ^0.16.1
  carousel_slider: ^2.2.1
  cached_network_image: ^2.3.2+1
  permission_handler: 5.0.1+1
  url_launcher: ^5.7.1
  lottie: ^0.6.0
  animations: ^1.1.2
  table_calendar: ^2.2.3
  charts_flutter: ^0.9.0
  package_info: ^0.4.3+2
  pub_semver: ^1.4.4
  fluttertoast: ^7.1.6

  flutter_launcher_icons: ^0.7.5
  rename: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/lottie/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/upload-icon.png
    - assets/images/apple-logo.png
    - assets/images/google-logo.png
    - assets/lottie/loading.json
