name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: install dependencies
        run: flutter pub get
        working-directory: ./flutter
      - name: test
        run: flutter test
        working-directory: ./flutter

